#!/bin/bash

export PROJECT_PATH=$(pwd)

while [[ $# -gt 0 ]]; do 
  case $1 in
    -U)
      python ~/atambibki/src/refresh_database.py 
      shift
      shift
      ;;

    -n)
      biber $2 > ~/atambibki/misc/temp_biber.txt
      python ~/atambibki/src/get_refs.py 
      shift
      shift
      ;;
  esac
done
